### PR TITLE
Remove transit popups from screen readers

### PR DESCRIPTION
**Pull request by mikkoisa**
From accessibility report 3.1

### CODE REVIEW

**Review by Dremars — CHANGES_REQUESTED** [review]
This doesn't seem to fix problem. Transit stop markers themselves are read as numbers. This is probably because they have following styles `.icon-icon-hsl-bus:before {
    content: "2"; }`
Which I guess is used to figure out which icon to use? But these markers should be `aria-hidden` or they are read as "1", "2" etc.

**Comment by Dremars** [comment]
There are also some empty elements in bottom right controls. I'm not sure which ones are causing that

**Comment by mikkoisa** [comment]
@Dremars I see, didn't realise that the numbers were visible to screen readers. Fixed the problem

**Review by Dremars — CHANGES_REQUESTED** [review]
Transit icons are still read as numbers. Problem is that icon itself is aria-hidden but transit icons have 2 spans one is `transitBackground` which is not aria-hidden this should be changed to aria-hidden as well. It's in getTransitIcon function.

**Comment by mikkoisa** [comment]
@Dremars Fixed the background span too. Safari + Voiceover didn't have this issue, so I didn't notice it at all.

**Review by Dremars — APPROVED** [review]
@mikkoisa Interesting how differently all these work. :smile: But now it works perfectly with NVDA as well

**Pull request merged**
