### PR TITLE
Fix/map marker handling

### PR DESCRIPTION
**Pull request by Dremars**
- Changing map marker handling to not remove search results when browsing results by selecting specific units. Selected unit is also highlighted by tooltip above cluster if marker is inside it.
- Changed new search to remove selected unit so it doesn't show tooltip on new results

### CODE REVIEW

**Comment by Dremars** [comment]
[(2) Haun löytämät toimipisteet näytetään kartalla kunnes käyttäjä tekee uuden haun tai siirtyy etusivulle](https://trello.com/c/7v1CMXQP/111-2-haun-l%C3%B6yt%C3%A4m%C3%A4t-toimipisteet-n%C3%A4ytet%C3%A4%C3%A4n-kartalla-kunnes-k%C3%A4ytt%C3%A4j%C3%A4-tekee-uuden-haun-tai-siirtyy-etusivulle)

**Review by mikkoisa — CHANGES_REQUESTED** [review]
I really like this implementation! It is much easier to use the map when it is not zooming all the time. I noticed two bugs: Marker cluster hover seems to be broken (no hover popup at all). Also choosing a unit from search results, then going back to results page does not clear highlighted unit (tooltip stays on map).

**Comment by mikkoisa** [comment]
We should also discuss the case where user selects unit from result page and the unit is not visible on the chosen zoom level/map position. Since we are no longer zooming on the unit, the user might have problems finding it on the map.

**Comment by Dremars** [comment]
> I really like this implementation! It is much easier to use the map when it is not zooming all the time. I noticed two bugs: Marker cluster hover seems to be broken (no hover popup at all). Also choosing a unit from search results, then going back to results page does not clear highlighted unit (tooltip stays on map).

@mikkoisa 
Marker cluster hover has been activated once again (3e93589)
Hightlighted unit tooltip is hidden unless on unit page (2b2bf50)

**Review by mikkoisa — APPROVED** [review]

**Review by mikkoisa — APPROVED** [review]

**Pull request merged**
