### PR TITLE
Add other dynamic settings 

### PR DESCRIPTION
**Pull request by Arj-Peshtani**
Add dynamic settings for: 
- External translations
- Show/Hide area selection and nearby services
- Link to additional feedback info
- Show/Hide read speaker button in unit view

### CODE REVIEW

**Review by Dremars — CHANGES_REQUESTED** [review]
This doesn't seem feasible. I don't want us to start inserting individual translation into configuration file. We need to figure out some other way to insert translations. Maybe we can use configuration to add url for external translation JSON-file that is combined with our translation file? `const englishTranslations = { ...translations, ...overridingExternalTranslations } `  Or possibly just make the translation file configurable? 

I'm not entirely sure how this should be done but this doesn't seem to be it.

**Comment by Arj-Peshtani** [comment]
I chose to follow your suggestion to add external json files for the translations. I have also added some other changes that need to be configurable for the city of Turku. Can you review it again, please? @Dremars

**Review by Dremars — CHANGES_REQUESTED** [review]
@Arj-Peshtani Think we should avoid having city specific external translation files in git. I tried removing those files and using try-catch when requiring external translations. Seems to work fine except for a warning in build. So that could work.

Otherwise this looks good!

**Comment by Arj-Peshtani** [comment]
@Dremars just removed the files and added try-catch when requiring external translations.

**Review by Dremars — APPROVED** [review]
Looks good. 

@mikkoisa Can you give a fast look and then lets merge this.

**Review by mikkoisa — APPROVED** [review]
Looks really good now, approved!

**Pull request merged**
