### PR TITLE
New PanControl component for panning leaflet map

### PR DESCRIPTION
**Pull request by Dremars**
New PanControl component for handling map panning with keyboard.

~Still need to add direct keyboard handling for moving map with arrow keys.~ Added in 058ef1e

### CODE REVIEW

**Comment by Dremars** [comment]
[(3) Kartan navigointipainikkeet](https://trello.com/c/Uz9E5IkD/560-3-kartan-navigointipainikkeet)

**Review by mikkoisa — COMMENTED** [review]
Looks good! Should we consider centering the map buttons by adding margin to the other buttons?  
Näyttökuva 2021-3-10 kello 8 10 41

**Comment by Dremars** [comment]
Fixed control stylings 9756419 and fixed issue with leaflet maptype change causing adjusted styles to disappear 577ceab

**Review by mikkoisa — APPROVED** [review]
Looks good and works well! We could also at some pint add similar key press handlers for "+" and "-" keys that would zoom the map.

**Pull request merged**
