### PR TITLE
Search bar accessibility

### PR DESCRIPTION
**Pull request by mikkoisa**
Changed search bar suggestion implementation: 
- Use aria-owns and aria-activedescendant on input field to correctly link suggestions to search bar
- Use role="listbox" and role="option" on suggestion box and items
- Modify search bar component to use ref to control input field instead of state
- Browsing suggestions with keyboard no longer replaces search bar text. Old version did not work correctly on Voiceover. Now correct aria roles handle communication to screen reader users

These changes should also improve search bar usability on other screen readers

~~Note: Mobile version will be checked once PR#558 is merged~~

### CODE REVIEW

**Comment by mikkoisa** [comment]
[Hakukentän saavutettavuus](https://trello.com/c/ZxpBVhqA/773-hakukent%C3%A4n-saavutettavuus)

**Comment by mikkoisa** [comment]
Merged PR [#558](https://github.com/City-of-Helsinki/servicemap-ui/pull/558) to this. Four first commits are from this other PR.

**Comment by mikkoisa** [comment]
More discussion in https://github.com/City-of-Helsinki/servicemap-ui/pull/558

**Comment by mikkoisa** [comment]
[Tarkenna painike mobiiliversion hakuehdotuksissa ei toimi ruudunlukijalla (VoiceOver)](https://trello.com/c/CST6vcWO/760-tarkenna-painike-mobiiliversion-hakuehdotuksissa-ei-toimi-ruudunlukijalla-voiceover)

**Review by Dremars — COMMENTED** [review]
Seems mostly fine but I'm having issue with  Android TalkBack v7 where suggestion view is opened on focus and then there's no way to get out of the suggestion without selecting a suggestion or doing actual search. This causes issue where user can't get past search field since it's before results and is opened on focus.

Do you have this problem on your devices?

**Comment by Dremars** [comment]
Temporary fix coming in #571 Afterwards we need to figure out a way to solve this issue properly

**Review by Dremars — APPROVED** [review]

**Pull request merged**
