### PR TITLE
Fix/list item stylings

### PR DESCRIPTION
**Pull request by Dremars**
- Fix ResultItem and SimpleListItem stylings
- Add style variation option for ResultItem

### CODE REVIEW

**Comment by Dremars** [comment]
[Tapahtumasivun korjaukset](https://trello.com/c/1aeLHfIQ/322-tapahtumasivun-korjaukset)

**Comment by mikkoisa** [comment]
Also the left side padding in services in search results page should be checked.
Näyttökuva 2020-1-16 kello 13 03 53

**Comment by mikkoisa** [comment]
These list items are also a bit too much to the left (they should be on the right side of the title)
Näyttökuva 2020-1-16 kello 13 08 31

**Comment by Dremars** [comment]
@mikkoisa I've unified simple list items and result items to have unified styling and aligned items with TitledList title. List item hover area doesn't fill whole width because parent container has padding. Fixing this would require checking whole page layout. This is also issue in current version and should be checked separately.

**Pull request merged**
