### PR TITLE
Unit contract type municipality

### PR DESCRIPTION
**Pull request by mikkoisa**
Added municipality text next to contract type text.

### CODE REVIEW

**Comment by mikkoisa** [comment]
[(2) Kuntatieto sopimuslajin yhteyteen](https://trello.com/c/ivg765Oq/692-2-kuntatieto-sopimuslajin-yhteyteen)

**Review by Dremars — COMMENTED** [review]
Seems to work mostly fine. Noticed how some searches like "laboratorio" doesn't show municipality text. They have municipality for unit object but department municipality is `null`

But I guess this is desired outcome?

**Comment by mikkoisa** [comment]
@Dremars I think it is safer to display nothing than possibly incorrect information in that case. Municipality text is also hidden if we don't have translations for the city or if contract type is something else than municipal_service or purchase_service.

This got me thinking, should we change it to always show city name next to contract type if department municipality has value? Instead of just limiting it to those two contract types (municipal_service, purchase_service)

**Comment by Dremars** [comment]
>This got me thinking, should we change it to always show city name next to contract type if department municipality has value? >Instead of just limiting it to those two contract types (municipal_service, purchase_service)

I'm not sure. Should propable ask from Mirjam.  But otherwise this looks good.

**Comment by mikkoisa** [comment]
Decided that we will use department data instead of ID's to define if municipality should be shown.

**Review by Dremars — APPROVED** [review]

**Pull request merged**
